-- ============================================================================
-- CAPA BRONZE -- copia fiel de lo que devuelve Sage 50.
--
-- GENERADO por modelo/generar_bronze.py a partir de los *_schema.json que
-- deja extraer_y_guardar.py. NO EDITAR A MANO -- correr el generador de
-- nuevo si el esquema de Sage cambia (otra version, otro PH con columnas
-- custom). El archivo resultante es DDL valido, igual que si se hubiera
-- escrito a mano; lo unico que cambia es quien lo escribio.
--
-- REGLA DE ESTA CAPA (sigue vigente, el generador no la rompe): no se
-- transforma nada. Todas las columnas de cada tabla, mas metadata de carga.
--
-- Las columnas de fecha (DATE/TIMESTAMP en Sage) y las binarias (BINARY,
-- ej. GUIDs) llegan como VARCHAR -- la extraccion las convierte a texto
-- antes de escribir el JSON (ver extractores/_comun.py:_valor_json). El
-- parseo real es trabajo de staging, no de bronze.
--
-- AISLAMIENTO: se despliega una vez por propiedad en su propio workspace.
-- Ver ARQUITECTURA.md.
-- ============================================================================

CREATE SCHEMA bronze;
GO

-- ============================================================================
-- METADATA DE CARGA -- las cinco columnas con prefijo _ que llevan todas las
-- tablas de esta capa. Ver la nota completa sobre _propiedad_origen en
-- ARQUITECTURA.md -- es una ASERCION para detectar mezcla entre PH, nunca
-- una dimension para filtrar.
-- ============================================================================


-- bronze.chart -- 185 columnas de Sage + metadata.
-- Generado por modelo/generar_bronze.py, no editar a mano.
CREATE TABLE bronze.chart (
    "AccountID" VARCHAR(15) NULL,
    "AccountType" SMALLINT NULL,
    "AccountDescription" VARCHAR(30) NULL,
    "AccountIsInactive" TINYINT NULL,
    "GUID" VARCHAR(32) NULL,
    "GLAcntNumber" INT NULL,
    "Balance0Dr" DECIMAL(19,4) NULL,
    "Balance0Cr" DECIMAL(19,4) NULL,
    "Balance0Net" DECIMAL(19,4) NULL,
    "Balance1Dr" DECIMAL(19,4) NULL,
    "Balance1Cr" DECIMAL(19,4) NULL,
    "Balance1Net" DECIMAL(19,4) NULL,
    "Balance2Dr" DECIMAL(19,4) NULL,
    "Balance2Cr" DECIMAL(19,4) NULL,
    "Balance2Net" DECIMAL(19,4) NULL,
    "Balance3Dr" DECIMAL(19,4) NULL,
    "Balance3Cr" DECIMAL(19,4) NULL,
    "Balance3Net" DECIMAL(19,4) NULL,
    "Balance4Dr" DECIMAL(19,4) NULL,
    "Balance4Cr" DECIMAL(19,4) NULL,
    "Balance4Net" DECIMAL(19,4) NULL,
    "Balance5Dr" DECIMAL(19,4) NULL,
    "Balance5Cr" DECIMAL(19,4) NULL,
    "Balance5Net" DECIMAL(19,4) NULL,
    "Balance6Dr" DECIMAL(19,4) NULL,
    "Balance6Cr" DECIMAL(19,4) NULL,
    "Balance6Net" DECIMAL(19,4) NULL,
    "Balance7Dr" DECIMAL(19,4) NULL,
    "Balance7Cr" DECIMAL(19,4) NULL,
    "Balance7Net" DECIMAL(19,4) NULL,
    "Balance8Dr" DECIMAL(19,4) NULL,
    "Balance8Cr" DECIMAL(19,4) NULL,
    "Balance8Net" DECIMAL(19,4) NULL,
    "Balance9Dr" DECIMAL(19,4) NULL,
    "Balance9Cr" DECIMAL(19,4) NULL,
    "Balance9Net" DECIMAL(19,4) NULL,
    "Balance10Dr" DECIMAL(19,4) NULL,
    "Balance10Cr" DECIMAL(19,4) NULL,
    "Balance10Net" DECIMAL(19,4) NULL,
    "Balance11Dr" DECIMAL(19,4) NULL,
    "Balance11Cr" DECIMAL(19,4) NULL,
    "Balance11Net" DECIMAL(19,4) NULL,
    "Balance12Dr" DECIMAL(19,4) NULL,
    "Balance12Cr" DECIMAL(19,4) NULL,
    "Balance12Net" DECIMAL(19,4) NULL,
    "Balance13Dr" DECIMAL(19,4) NULL,
    "Balance13Cr" DECIMAL(19,4) NULL,
    "Balance13Net" DECIMAL(19,4) NULL,
    "Balance14Dr" DECIMAL(19,4) NULL,
    "Balance14Cr" DECIMAL(19,4) NULL,
    "Balance14Net" DECIMAL(19,4) NULL,
    "Balance15Dr" DECIMAL(19,4) NULL,
    "Balance15Cr" DECIMAL(19,4) NULL,
    "Balance15Net" DECIMAL(19,4) NULL,
    "Balance16Dr" DECIMAL(19,4) NULL,
    "Balance16Cr" DECIMAL(19,4) NULL,
    "Balance16Net" DECIMAL(19,4) NULL,
    "Balance17Dr" DECIMAL(19,4) NULL,
    "Balance17Cr" DECIMAL(19,4) NULL,
    "Balance17Net" DECIMAL(19,4) NULL,
    "Balance18Dr" DECIMAL(19,4) NULL,
    "Balance18Cr" DECIMAL(19,4) NULL,
    "Balance18Net" DECIMAL(19,4) NULL,
    "Balance19Dr" DECIMAL(19,4) NULL,
    "Balance19Cr" DECIMAL(19,4) NULL,
    "Balance19Net" DECIMAL(19,4) NULL,
    "Balance20Dr" DECIMAL(19,4) NULL,
    "Balance20Cr" DECIMAL(19,4) NULL,
    "Balance20Net" DECIMAL(19,4) NULL,
    "Balance21Dr" DECIMAL(19,4) NULL,
    "Balance21Cr" DECIMAL(19,4) NULL,
    "Balance21Net" DECIMAL(19,4) NULL,
    "Balance22Dr" DECIMAL(19,4) NULL,
    "Balance22Cr" DECIMAL(19,4) NULL,
    "Balance22Net" DECIMAL(19,4) NULL,
    "Balance23Dr" DECIMAL(19,4) NULL,
    "Balance23Cr" DECIMAL(19,4) NULL,
    "Balance23Net" DECIMAL(19,4) NULL,
    "Balance24Dr" DECIMAL(19,4) NULL,
    "Balance24Cr" DECIMAL(19,4) NULL,
    "Balance24Net" DECIMAL(19,4) NULL,
    "Balance25Dr" DECIMAL(19,4) NULL,
    "Balance25Cr" DECIMAL(19,4) NULL,
    "Balance25Net" DECIMAL(19,4) NULL,
    "Balance26Dr" DECIMAL(19,4) NULL,
    "Balance26Cr" DECIMAL(19,4) NULL,
    "Balance26Net" DECIMAL(19,4) NULL,
    "Balance27Dr" DECIMAL(19,4) NULL,
    "Balance27Cr" DECIMAL(19,4) NULL,
    "Balance27Net" DECIMAL(19,4) NULL,
    "Balance28Dr" DECIMAL(19,4) NULL,
    "Balance28Cr" DECIMAL(19,4) NULL,
    "Balance28Net" DECIMAL(19,4) NULL,
    "Balance29Dr" DECIMAL(19,4) NULL,
    "Balance29Cr" DECIMAL(19,4) NULL,
    "Balance29Net" DECIMAL(19,4) NULL,
    "Balance30Dr" DECIMAL(19,4) NULL,
    "Balance30Cr" DECIMAL(19,4) NULL,
    "Balance30Net" DECIMAL(19,4) NULL,
    "Balance31Dr" DECIMAL(19,4) NULL,
    "Balance31Cr" DECIMAL(19,4) NULL,
    "Balance31Net" DECIMAL(19,4) NULL,
    "Balance32Dr" DECIMAL(19,4) NULL,
    "Balance32Cr" DECIMAL(19,4) NULL,
    "Balance32Net" DECIMAL(19,4) NULL,
    "Balance33Dr" DECIMAL(19,4) NULL,
    "Balance33Cr" DECIMAL(19,4) NULL,
    "Balance33Net" DECIMAL(19,4) NULL,
    "Balance34Dr" DECIMAL(19,4) NULL,
    "Balance34Cr" DECIMAL(19,4) NULL,
    "Balance34Net" DECIMAL(19,4) NULL,
    "Balance35Dr" DECIMAL(19,4) NULL,
    "Balance35Cr" DECIMAL(19,4) NULL,
    "Balance35Net" DECIMAL(19,4) NULL,
    "Balance36Dr" DECIMAL(19,4) NULL,
    "Balance36Cr" DECIMAL(19,4) NULL,
    "Balance36Net" DECIMAL(19,4) NULL,
    "Balance37Dr" DECIMAL(19,4) NULL,
    "Balance37Cr" DECIMAL(19,4) NULL,
    "Balance37Net" DECIMAL(19,4) NULL,
    "Balance38Dr" DECIMAL(19,4) NULL,
    "Balance38Cr" DECIMAL(19,4) NULL,
    "Balance38Net" DECIMAL(19,4) NULL,
    "Balance39Dr" DECIMAL(19,4) NULL,
    "Balance39Cr" DECIMAL(19,4) NULL,
    "Balance39Net" DECIMAL(19,4) NULL,
    "Balance40Dr" DECIMAL(19,4) NULL,
    "Balance40Cr" DECIMAL(19,4) NULL,
    "Balance40Net" DECIMAL(19,4) NULL,
    "Balance41Dr" DECIMAL(19,4) NULL,
    "Balance41Cr" DECIMAL(19,4) NULL,
    "Balance41Net" DECIMAL(19,4) NULL,
    "TaxCode" VARCHAR(12) NULL,
    "NextCheckNumber" VARCHAR(20) NULL,
    "GL1099Index" SMALLINT NULL,
    "ReceiptNum" VARCHAR(20) NULL,
    "LastDepositTicket" VARCHAR(20) NULL,
    "NextEmailReceipt" VARCHAR(20) NULL,
    "LastUpdateCounter" INT NULL,
    "HasPurgedTrx" VARCHAR(32) NULL,
    "PurgedBalance0Dr" DECIMAL(19,4) NULL,
    "PurgedBalance0Cr" DECIMAL(19,4) NULL,
    "PurgedBalance0Net" DECIMAL(19,4) NULL,
    "PurgedBalance1Dr" DECIMAL(19,4) NULL,
    "PurgedBalance1Cr" DECIMAL(19,4) NULL,
    "PurgedBalance1Net" DECIMAL(19,4) NULL,
    "PurgedBalance2Dr" DECIMAL(19,4) NULL,
    "PurgedBalance2Cr" DECIMAL(19,4) NULL,
    "PurgedBalance2Net" DECIMAL(19,4) NULL,
    "PurgedBalance3Dr" DECIMAL(19,4) NULL,
    "PurgedBalance3Cr" DECIMAL(19,4) NULL,
    "PurgedBalance3Net" DECIMAL(19,4) NULL,
    "PurgedBalance4Dr" DECIMAL(19,4) NULL,
    "PurgedBalance4Cr" DECIMAL(19,4) NULL,
    "PurgedBalance4Net" DECIMAL(19,4) NULL,
    "PurgedBalance5Dr" DECIMAL(19,4) NULL,
    "PurgedBalance5Cr" DECIMAL(19,4) NULL,
    "PurgedBalance5Net" DECIMAL(19,4) NULL,
    "PurgedBalance6Dr" DECIMAL(19,4) NULL,
    "PurgedBalance6Cr" DECIMAL(19,4) NULL,
    "PurgedBalance6Net" DECIMAL(19,4) NULL,
    "PurgedBalance7Dr" DECIMAL(19,4) NULL,
    "PurgedBalance7Cr" DECIMAL(19,4) NULL,
    "PurgedBalance7Net" DECIMAL(19,4) NULL,
    "PurgedBalance8Dr" DECIMAL(19,4) NULL,
    "PurgedBalance8Cr" DECIMAL(19,4) NULL,
    "PurgedBalance8Net" DECIMAL(19,4) NULL,
    "PurgedBalance9Dr" DECIMAL(19,4) NULL,
    "PurgedBalance9Cr" DECIMAL(19,4) NULL,
    "PurgedBalance9Net" DECIMAL(19,4) NULL,
    "PurgedBalance10Dr" DECIMAL(19,4) NULL,
    "PurgedBalance10Cr" DECIMAL(19,4) NULL,
    "PurgedBalance10Net" DECIMAL(19,4) NULL,
    "PurgedBalance11Dr" DECIMAL(19,4) NULL,
    "PurgedBalance11Cr" DECIMAL(19,4) NULL,
    "PurgedBalance11Net" DECIMAL(19,4) NULL,
    "PurgedBalance12Dr" DECIMAL(19,4) NULL,
    "PurgedBalance12Cr" DECIMAL(19,4) NULL,
    "PurgedBalance12Net" DECIMAL(19,4) NULL,
    "PurgedBalance13Dr" DECIMAL(19,4) NULL,
    "PurgedBalance13Cr" DECIMAL(19,4) NULL,
    "PurgedBalance13Net" DECIMAL(19,4) NULL,
    "PurgedBalance14Dr" DECIMAL(19,4) NULL,
    "PurgedBalance14Cr" DECIMAL(19,4) NULL,
    "PurgedBalance14Net" DECIMAL(19,4) NULL,
    "_lote_id" VARCHAR(40) NOT NULL,
    "_propiedad_origen" VARCHAR(30) NOT NULL,
    "_dsn_origen" VARCHAR(50) NOT NULL,
    "_archivo_origen" VARCHAR(400) NOT NULL,
    "_cargado_en" DATETIME2(3) NOT NULL
);
GO

-- bronze.customers -- 153 columnas de Sage + metadata.
-- Generado por modelo/generar_bronze.py, no editar a mano.
CREATE TABLE bronze.customers (
    "CustomerID" VARCHAR(20) NULL,
    "Customer_Type" VARCHAR(8) NULL,
    "Contact" VARCHAR(20) NULL,
    "Phone_Number" VARCHAR(20) NULL,
    "FAX_Number" VARCHAR(20) NULL,
    "SalesTaxResaleNum" VARCHAR(20) NULL,
    "AccountNumber" VARCHAR(25) NULL,
    "CustomerUnused0" TINYINT NULL,
    "Use_Std_Terms" TINYINT NULL,
    "GLAcntNumber" INT NULL,
    "GUID" VARCHAR(32) NULL,
    "Balance" DECIMAL(19,4) NULL,
    "CustomerSince" VARCHAR(30) NULL,
    "Sales1" DECIMAL(19,4) NULL,
    "Sales2" DECIMAL(19,4) NULL,
    "Sales3" DECIMAL(19,4) NULL,
    "Sales4" DECIMAL(19,4) NULL,
    "Sales5" DECIMAL(19,4) NULL,
    "Sales6" DECIMAL(19,4) NULL,
    "Sales7" DECIMAL(19,4) NULL,
    "Sales8" DECIMAL(19,4) NULL,
    "Sales9" DECIMAL(19,4) NULL,
    "Sales10" DECIMAL(19,4) NULL,
    "Sales11" DECIMAL(19,4) NULL,
    "Sales12" DECIMAL(19,4) NULL,
    "Sales13" DECIMAL(19,4) NULL,
    "Sales14" DECIMAL(19,4) NULL,
    "Sales15" DECIMAL(19,4) NULL,
    "Sales16" DECIMAL(19,4) NULL,
    "Sales17" DECIMAL(19,4) NULL,
    "Sales18" DECIMAL(19,4) NULL,
    "Sales19" DECIMAL(19,4) NULL,
    "Sales20" DECIMAL(19,4) NULL,
    "Sales21" DECIMAL(19,4) NULL,
    "Sales22" DECIMAL(19,4) NULL,
    "Sales23" DECIMAL(19,4) NULL,
    "Sales24" DECIMAL(19,4) NULL,
    "Sales25" DECIMAL(19,4) NULL,
    "Sales26" DECIMAL(19,4) NULL,
    "Sales27" DECIMAL(19,4) NULL,
    "Sales28" DECIMAL(19,4) NULL,
    "Sales29" DECIMAL(19,4) NULL,
    "Sales30" DECIMAL(19,4) NULL,
    "Sales31" DECIMAL(19,4) NULL,
    "Sales32" DECIMAL(19,4) NULL,
    "Sales33" DECIMAL(19,4) NULL,
    "Sales34" DECIMAL(19,4) NULL,
    "Sales35" DECIMAL(19,4) NULL,
    "Sales36" DECIMAL(19,4) NULL,
    "Sales37" DECIMAL(19,4) NULL,
    "Sales38" DECIMAL(19,4) NULL,
    "Sales39" DECIMAL(19,4) NULL,
    "Sales40" DECIMAL(19,4) NULL,
    "Sales41" DECIMAL(19,4) NULL,
    "Sales42" DECIMAL(19,4) NULL,
    "Payments1" DECIMAL(19,4) NULL,
    "Payments2" DECIMAL(19,4) NULL,
    "Payments3" DECIMAL(19,4) NULL,
    "Payments4" DECIMAL(19,4) NULL,
    "Payments5" DECIMAL(19,4) NULL,
    "Payments6" DECIMAL(19,4) NULL,
    "Payments7" DECIMAL(19,4) NULL,
    "Payments8" DECIMAL(19,4) NULL,
    "Payments9" DECIMAL(19,4) NULL,
    "Payments10" DECIMAL(19,4) NULL,
    "Payments11" DECIMAL(19,4) NULL,
    "Payments12" DECIMAL(19,4) NULL,
    "Payments13" DECIMAL(19,4) NULL,
    "Payments14" DECIMAL(19,4) NULL,
    "Payments15" DECIMAL(19,4) NULL,
    "Payments16" DECIMAL(19,4) NULL,
    "Payments17" DECIMAL(19,4) NULL,
    "Payments18" DECIMAL(19,4) NULL,
    "Payments19" DECIMAL(19,4) NULL,
    "Payments20" DECIMAL(19,4) NULL,
    "Payments21" DECIMAL(19,4) NULL,
    "Payments22" DECIMAL(19,4) NULL,
    "Payments23" DECIMAL(19,4) NULL,
    "Payments24" DECIMAL(19,4) NULL,
    "Payments25" DECIMAL(19,4) NULL,
    "Payments26" DECIMAL(19,4) NULL,
    "Payments27" DECIMAL(19,4) NULL,
    "Payments28" DECIMAL(19,4) NULL,
    "Payments29" DECIMAL(19,4) NULL,
    "Payments30" DECIMAL(19,4) NULL,
    "Payments31" DECIMAL(19,4) NULL,
    "Payments32" DECIMAL(19,4) NULL,
    "Payments33" DECIMAL(19,4) NULL,
    "Payments34" DECIMAL(19,4) NULL,
    "Payments35" DECIMAL(19,4) NULL,
    "Payments36" DECIMAL(19,4) NULL,
    "Payments37" DECIMAL(19,4) NULL,
    "Payments38" DECIMAL(19,4) NULL,
    "Payments39" DECIMAL(19,4) NULL,
    "Payments40" DECIMAL(19,4) NULL,
    "Payments41" DECIMAL(19,4) NULL,
    "Payments42" DECIMAL(19,4) NULL,
    "LastInvoiceDate" VARCHAR(30) NULL,
    "Last_Invoice_Amt" DECIMAL(19,4) NULL,
    "Last_Pmnt_Date" VARCHAR(30) NULL,
    "Last_Pmnt_Amnt" DECIMAL(19,4) NULL,
    "LastStatementDate" VARCHAR(30) NULL,
    "Terms_DueDays" SMALLINT NULL,
    "Terms_DiscDays" SMALLINT NULL,
    "Terms_DiscountPcnt" DECIMAL(19,4) NULL,
    "Terms_CreditLimit" DECIMAL(19,4) NULL,
    "Terms_ChgInterest" TINYINT NULL,
    "Terms_COD" TINYINT NULL,
    "Terms_Prepay" TINYINT NULL,
    "TermsDaysAreActual" TINYINT NULL,
    "TermsDueAtMonthEnd" TINYINT NULL,
    "Terms_Unused" VARCHAR(6) NULL,
    "CustomerIsInactive" TINYINT NULL,
    "PhoneNumber2" VARCHAR(20) NULL,
    "Customer_Bill_Name" VARCHAR(39) NULL,
    "CustomField1" VARCHAR(40) NULL,
    "CustomField2" VARCHAR(40) NULL,
    "CustomField3" VARCHAR(40) NULL,
    "CustomField4" VARCHAR(40) NULL,
    "CustomField5" VARCHAR(40) NULL,
    "EmpRecordNumber" INT NULL,
    "OpenPO" VARCHAR(20) NULL,
    "WhichShipVia" VARCHAR(20) NULL,
    "IsProspect" TINYINT NULL,
    "PriceLevel" SMALLINT NULL,
    "eMail_Address" VARCHAR(64) NULL,
    "CustomerRecordNumber" INT NULL,
    "WEB_Address" VARCHAR(255) NULL,
    "BillPresentmentEnabl" TINYINT NULL,
    "UsePaymentDefaults" INT NULL,
    "Cardholder_Name" VARCHAR(39) NULL,
    "Cardholder_Address1" VARCHAR(50) NULL,
    "Cardholder_Address2" VARCHAR(50) NULL,
    "Cardholder_City" VARCHAR(20) NULL,
    "Cardholder_State" VARCHAR(2) NULL,
    "Cardholder_ZIP" VARCHAR(12) NULL,
    "Cardholder_Country" VARCHAR(15) NULL,
    "CcStoredAcctRef" VARCHAR(32) NULL,
    "CcMaskedNumber" VARCHAR(30) NULL,
    "CcExpireDate" VARCHAR(30) NULL,
    "UsePMAndCAPaymentDef" INT NULL,
    "DefaultPaymentMethod" VARCHAR(20) NULL,
    "DefCashAcct_RecNum" INT NULL,
    "FlagsFormDelivery" INT NULL,
    "LastUpdateCounter" INT NULL,
    "CreditStatus" INT NULL,
    "ReplaceItemIDFormOpt" INT NULL,
    "NumOfPaidInvoices" INT NULL,
    "DaysToPayInvoices" INT NULL,
    "LastSavedAt" VARCHAR(30) NULL,
    "CreditStatusMsg" VARCHAR(250) NULL,
    "ACHStoredAcctRef" VARCHAR(32) NULL,
    "MaskedBankAcctNum" VARCHAR(30) NULL,
    "_lote_id" VARCHAR(40) NOT NULL,
    "_propiedad_origen" VARCHAR(30) NOT NULL,
    "_dsn_origen" VARCHAR(50) NOT NULL,
    "_archivo_origen" VARCHAR(400) NOT NULL,
    "_cargado_en" DATETIME2(3) NOT NULL
);
GO

-- bronze.vendors -- 139 columnas de Sage + metadata.
-- Generado por modelo/generar_bronze.py, no editar a mano.
CREATE TABLE bronze.vendors (
    "VendorID" VARCHAR(20) NULL,
    "GUID" VARCHAR(32) NULL,
    "Name" VARCHAR(39) NULL,
    "VendorType" VARCHAR(8) NULL,
    "Contact" VARCHAR(20) NULL,
    "PhoneNumber" VARCHAR(20) NULL,
    "FAXNumber" VARCHAR(20) NULL,
    "FederalEIN" VARCHAR(20) NULL,
    "Unused_1" VARCHAR(20) NULL,
    "Unused_2" TINYINT NULL,
    "UseStdTerms" TINYINT NULL,
    "GLAcntNumber" INT NULL,
    "UnusedSalesTaxID" VARCHAR(8) NULL,
    "Balance" DECIMAL(19,4) NULL,
    "VendorSince" VARCHAR(30) NULL,
    "Purchases1" DECIMAL(19,4) NULL,
    "Purchases2" DECIMAL(19,4) NULL,
    "Purchases3" DECIMAL(19,4) NULL,
    "Purchases4" DECIMAL(19,4) NULL,
    "Purchases5" DECIMAL(19,4) NULL,
    "Purchases6" DECIMAL(19,4) NULL,
    "Purchases7" DECIMAL(19,4) NULL,
    "Purchases8" DECIMAL(19,4) NULL,
    "Purchases9" DECIMAL(19,4) NULL,
    "Purchases10" DECIMAL(19,4) NULL,
    "Purchases11" DECIMAL(19,4) NULL,
    "Purchases12" DECIMAL(19,4) NULL,
    "Purchases13" DECIMAL(19,4) NULL,
    "Purchases14" DECIMAL(19,4) NULL,
    "Purchases15" DECIMAL(19,4) NULL,
    "Purchases16" DECIMAL(19,4) NULL,
    "Purchases17" DECIMAL(19,4) NULL,
    "Purchases18" DECIMAL(19,4) NULL,
    "Purchases19" DECIMAL(19,4) NULL,
    "Purchases20" DECIMAL(19,4) NULL,
    "Purchases21" DECIMAL(19,4) NULL,
    "Purchases22" DECIMAL(19,4) NULL,
    "Purchases23" DECIMAL(19,4) NULL,
    "Purchases24" DECIMAL(19,4) NULL,
    "Purchases25" DECIMAL(19,4) NULL,
    "Purchases26" DECIMAL(19,4) NULL,
    "Purchases27" DECIMAL(19,4) NULL,
    "Purchases28" DECIMAL(19,4) NULL,
    "Purchases29" DECIMAL(19,4) NULL,
    "Purchases30" DECIMAL(19,4) NULL,
    "Purchases31" DECIMAL(19,4) NULL,
    "Purchases32" DECIMAL(19,4) NULL,
    "Purchases33" DECIMAL(19,4) NULL,
    "Purchases34" DECIMAL(19,4) NULL,
    "Purchases35" DECIMAL(19,4) NULL,
    "Purchases36" DECIMAL(19,4) NULL,
    "Purchases37" DECIMAL(19,4) NULL,
    "Purchases38" DECIMAL(19,4) NULL,
    "Purchases39" DECIMAL(19,4) NULL,
    "Purchases40" DECIMAL(19,4) NULL,
    "Purchases41" DECIMAL(19,4) NULL,
    "Purchases42" DECIMAL(19,4) NULL,
    "Payments1" DECIMAL(19,4) NULL,
    "Payments2" DECIMAL(19,4) NULL,
    "Payments3" DECIMAL(19,4) NULL,
    "Payments4" DECIMAL(19,4) NULL,
    "Payments5" DECIMAL(19,4) NULL,
    "Payments6" DECIMAL(19,4) NULL,
    "Payments7" DECIMAL(19,4) NULL,
    "Payments8" DECIMAL(19,4) NULL,
    "Payments9" DECIMAL(19,4) NULL,
    "Payments10" DECIMAL(19,4) NULL,
    "Payments11" DECIMAL(19,4) NULL,
    "Payments12" DECIMAL(19,4) NULL,
    "Payments13" DECIMAL(19,4) NULL,
    "Payments14" DECIMAL(19,4) NULL,
    "Payments15" DECIMAL(19,4) NULL,
    "Payments16" DECIMAL(19,4) NULL,
    "Payments17" DECIMAL(19,4) NULL,
    "Payments18" DECIMAL(19,4) NULL,
    "Payments19" DECIMAL(19,4) NULL,
    "Payments20" DECIMAL(19,4) NULL,
    "Payments21" DECIMAL(19,4) NULL,
    "Payments22" DECIMAL(19,4) NULL,
    "Payments23" DECIMAL(19,4) NULL,
    "Payments24" DECIMAL(19,4) NULL,
    "Payments25" DECIMAL(19,4) NULL,
    "Payments26" DECIMAL(19,4) NULL,
    "Payments27" DECIMAL(19,4) NULL,
    "Payments28" DECIMAL(19,4) NULL,
    "Payments29" DECIMAL(19,4) NULL,
    "Payments30" DECIMAL(19,4) NULL,
    "Payments31" DECIMAL(19,4) NULL,
    "Payments32" DECIMAL(19,4) NULL,
    "Payments33" DECIMAL(19,4) NULL,
    "Payments34" DECIMAL(19,4) NULL,
    "Payments35" DECIMAL(19,4) NULL,
    "Payments36" DECIMAL(19,4) NULL,
    "Payments37" DECIMAL(19,4) NULL,
    "Payments38" DECIMAL(19,4) NULL,
    "Payments39" DECIMAL(19,4) NULL,
    "Payments40" DECIMAL(19,4) NULL,
    "Payments41" DECIMAL(19,4) NULL,
    "Payments42" DECIMAL(19,4) NULL,
    "Typeof1099" SMALLINT NULL,
    "LastInvoiceDate" VARCHAR(30) NULL,
    "LastInvoiceAmount" DECIMAL(19,4) NULL,
    "LastPaymentDate" VARCHAR(30) NULL,
    "LastPaymentAmount" DECIMAL(19,4) NULL,
    "DueDays" SMALLINT NULL,
    "DiscountDays" SMALLINT NULL,
    "DiscountPercent" DECIMAL(19,4) NULL,
    "CreditLimitNotUsed" DECIMAL(19,4) NULL,
    "UnusedCharge" TINYINT NULL,
    "TermsCOD" TINYINT NULL,
    "TermsPrepay" TINYINT NULL,
    "TermsDaysIsActual" TINYINT NULL,
    "TermsDueMonthEnd" TINYINT NULL,
    "TermsUnused" VARCHAR(6) NULL,
    "IsInactive" TINYINT NULL,
    "CustomField0" VARCHAR(40) NULL,
    "CustomField1" VARCHAR(40) NULL,
    "CustomField2" VARCHAR(40) NULL,
    "CustomField3" VARCHAR(40) NULL,
    "CustomField4" VARCHAR(40) NULL,
    "PhoneNumber2" VARCHAR(20) NULL,
    "ShipViaCode" VARCHAR(20) NULL,
    "OurAccountWithThem" VARCHAR(25) NULL,
    "VendorRecordNumber" INT NULL,
    "Email" VARCHAR(64) NULL,
    "WebAddress" VARCHAR(255) NULL,
    "EmpRecordNumber" INT NULL,
    "FlagsFormDelivery" INT NULL,
    "ReplaceItemIDFormOpt" INT NULL,
    "Shipments_AddrType" INT NULL,
    "PO_AddrType" INT NULL,
    "Payments_AddrType" INT NULL,
    "UseBillPay" TINYINT NULL,
    "UsePaymentDefaults" INT NULL,
    "DefaultPaymentMethod" INT NULL,
    "DefCashAcct_RecNum" INT NULL,
    "Notes" VARCHAR(255) NULL,
    "LastUpdateCounter" INT NULL,
    "LastSavedAt" VARCHAR(30) NULL,
    "_lote_id" VARCHAR(40) NOT NULL,
    "_propiedad_origen" VARCHAR(30) NOT NULL,
    "_dsn_origen" VARCHAR(50) NOT NULL,
    "_archivo_origen" VARCHAR(400) NOT NULL,
    "_cargado_en" DATETIME2(3) NOT NULL
);
GO

-- bronze.jrnlrow -- 47 columnas de Sage + metadata.
-- Generado por modelo/generar_bronze.py, no editar a mano.
CREATE TABLE bronze.jrnlrow (
    "GLAcntNumber" INT NULL,
    "PostOrder" INT NULL,
    "RowNumber" SMALLINT NULL,
    "ItemRecordNumber" INT NULL,
    "JobRecordNumber" INT NULL,
    "PhaseRecordNumber" INT NULL,
    "CostRecordNumber" INT NULL,
    "LinkToAnotherTrx" INT NULL,
    "LinkToOtherTrxIndex" SMALLINT NULL,
    "Journal" INT NULL,
    "RowDate" VARCHAR(30) NULL,
    "POSOIsClosed" TINYINT NULL,
    "IncludeInGL" INT NULL,
    "IncludeInInvLedger" INT NULL,
    "RowType" INT NULL,
    "Amount" DECIMAL(19,4) NULL,
    "StockingQuantity" DECIMAL(19,4) NULL,
    "StockingUnitCost" DECIMAL(19,4) NULL,
    "AmountReceived" DECIMAL(19,4) NULL,
    "StockingQtyReceived" DECIMAL(19,4) NULL,
    "DistNumber" SMALLINT NULL,
    "RowDescription" VARCHAR(160) NULL,
    "CustomerRecordNumber" INT NULL,
    "VendorRecordNumber" INT NULL,
    "EmpRecordNumber" INT NULL,
    "rGUIDa" INT NULL,
    "rGUID" VARCHAR(32) NULL,
    "rGUIDb" INT NULL,
    "rGUIDc" INT NULL,
    "rGUIDd" INT NULL,
    "UMGUID" VARCHAR(32) NULL,
    "UsedForReimbExp" TINYINT NULL,
    "TaxAuthorityCode" VARCHAR(8) NULL,
    "SalesTaxType" SMALLINT NULL,
    "PayrollFieldNumber" SMALLINT NULL,
    "InvNumForThisTrx" VARCHAR(20) NULL,
    "DateCleared" VARCHAR(30) NULL,
    "Quantity" DECIMAL(19,4) NULL,
    "QtyReceived" DECIMAL(19,4) NULL,
    "UnitCost" DECIMAL(19,4) NULL,
    "POCreated" TINYINT NULL,
    "HasSerialNumbers" TINYINT NULL,
    "RetainagePercent" DECIMAL(19,4) NULL,
    "LaborBurdenPercent" DECIMAL(19,4) NULL,
    "JournalRowEx" INT NULL,
    "LinkJournalRowEx" INT NULL,
    "LastUpdateCounter" INT NULL,
    "_lote_id" VARCHAR(40) NOT NULL,
    "_propiedad_origen" VARCHAR(30) NOT NULL,
    "_dsn_origen" VARCHAR(50) NOT NULL,
    "_archivo_origen" VARCHAR(400) NOT NULL,
    "_cargado_en" DATETIME2(3) NOT NULL
);
GO

-- bronze.jrnlhdr -- 168 columnas de Sage + metadata.
-- Generado por modelo/generar_bronze.py, no editar a mano.
CREATE TABLE bronze.jrnlhdr (
    "JrnlKey_Partner" TINYINT NULL,
    "BinaryJrnlKey" VARCHAR(32) NULL,
    "JrnlKey_TrxNumber" INT NULL,
    "JrnlKey_Per" SMALLINT NULL,
    "JrnlKey_Journal" SMALLINT NULL,
    "JrnlKey_Shadow" TINYINT NULL,
    "JournalEx" SMALLINT NULL,
    "Module" VARCHAR(1) NULL,
    "CustVendId" INT NULL,
    "TransactionDate" VARCHAR(30) NULL,
    "JournalGUID" VARCHAR(32) NULL,
    "PostOrder" INT NULL,
    "Description" VARCHAR(30) NULL,
    "MainAmount" DECIMAL(19,4) NULL,
    "Reference" VARCHAR(20) NULL,
    "TrxIsPosted" TINYINT NULL,
    "TrxIsPrepay" TINYINT NULL,
    "CannotBePurged" TINYINT NULL,
    "IsBegBal" TINYINT NULL,
    "SalesTaxCode" VARCHAR(8) NULL,
    "RecurNumber" INT NULL,
    "Recurr2" SMALLINT NULL,
    "EmpRecordNumber" INT NULL,
    "HasPartner" TINYINT NULL,
    "TrxIsReadOnly" SMALLINT NULL,
    "IsReversed" TINYINT NULL,
    "Memo" VARCHAR(30) NULL,
    "DepositTicketID" VARCHAR(20) NULL,
    "DepositDate" VARCHAR(30) NULL,
    "GLAcntNumber" INT NULL,
    "TrxName" VARCHAR(39) NULL,
    "TrxAddress1" VARCHAR(50) NULL,
    "TrxAddress2" VARCHAR(50) NULL,
    "TrxCity" VARCHAR(20) NULL,
    "TrxState" VARCHAR(2) NULL,
    "TrxZIP" VARCHAR(12) NULL,
    "TrxCountry" VARCHAR(15) NULL,
    "PaymentMethod" VARCHAR(20) NULL,
    "PayCustOrRecVend" SMALLINT NULL,
    "CustVendRecNumber" INT NULL,
    "PurchOrder" VARCHAR(20) NULL,
    "DateDue" VARCHAR(30) NULL,
    "DiscountDate" VARCHAR(30) NULL,
    "DiscountAmount" DECIMAL(19,4) NULL,
    "TermsDescription" VARCHAR(39) NULL,
    "GoodThruDate" VARCHAR(30) NULL,
    "PrintCommentAtEnd" TINYINT NULL,
    "IsDropShip" TINYINT NULL,
    "DropShipRecordNumber" INT NULL,
    "ShipToName" VARCHAR(39) NULL,
    "ShipToAddress1" VARCHAR(50) NULL,
    "ShipToAddress2" VARCHAR(50) NULL,
    "ShipToCity" VARCHAR(20) NULL,
    "ShipToState" VARCHAR(2) NULL,
    "ShipToZIP" VARCHAR(12) NULL,
    "ShipToCountry" VARCHAR(15) NULL,
    "ReceiptNum" VARCHAR(20) NULL,
    "ShipVia" VARCHAR(20) NULL,
    "QuoteIDForSales" VARCHAR(20) NULL,
    "ShipDate" VARCHAR(30) NULL,
    "MemorizedID" VARCHAR(20) NULL,
    "MemorizedShipToIndex" INT NULL,
    "MemorizRemitToIndex" INT NULL,
    "INV_POSOOrderNumber" VARCHAR(20) NULL,
    "WaitingForBill" TINYINT NULL,
    "CustomerInvoiceNo" VARCHAR(20) NULL,
    "CompletedDate" VARCHAR(30) NULL,
    "POSOisClosed" TINYINT NULL,
    "ElectronicPayment" TINYINT NULL,
    "DateSent" VARCHAR(30) NULL,
    "ElectronicID" VARCHAR(10) NULL,
    "AccountDescription" VARCHAR(21) NULL,
    "LastUsedDistNumber" SMALLINT NULL,
    "AmountPaid" DECIMAL(19,4) NULL,
    "TotalInvoicePaid" DECIMAL(19,4) NULL,
    "EndOfPayPeriod" VARCHAR(30) NULL,
    "WeeksWorked" SMALLINT NULL,
    "PRHours1" DECIMAL(19,4) NULL,
    "PRHours2" DECIMAL(19,4) NULL,
    "PRHours3" DECIMAL(19,4) NULL,
    "PRHours4" DECIMAL(19,4) NULL,
    "PRHours5" DECIMAL(19,4) NULL,
    "PRHours6" DECIMAL(19,4) NULL,
    "PRHours7" DECIMAL(19,4) NULL,
    "PRHours8" DECIMAL(19,4) NULL,
    "PRHours9" DECIMAL(19,4) NULL,
    "PRHours10" DECIMAL(19,4) NULL,
    "PRHours11" DECIMAL(19,4) NULL,
    "PRHours12" DECIMAL(19,4) NULL,
    "PRHours13" DECIMAL(19,4) NULL,
    "PRHours14" DECIMAL(19,4) NULL,
    "PRHours15" DECIMAL(19,4) NULL,
    "PRHours16" DECIMAL(19,4) NULL,
    "PRHours17" DECIMAL(19,4) NULL,
    "PRHours18" DECIMAL(19,4) NULL,
    "PRHours19" DECIMAL(19,4) NULL,
    "PRHours20" DECIMAL(19,4) NULL,
    "Comment" VARCHAR(2000) NULL,
    "TrxVoidedBy" INT NULL,
    "JrnlTypeEx" INT NULL,
    "CreditCardName" VARCHAR(39) NULL,
    "CreditCardAddress1" VARCHAR(50) NULL,
    "CreditCardAddress2" VARCHAR(50) NULL,
    "CreditCardCity" VARCHAR(20) NULL,
    "CreditCardState" VARCHAR(2) NULL,
    "CreditCardZIP" VARCHAR(12) NULL,
    "CreditCardCountry" VARCHAR(15) NULL,
    "CcStoredAcctRef" VARCHAR(32) NULL,
    "CreditCardMaskedNbr" VARCHAR(30) NULL,
    "CreditCardDate" VARCHAR(30) NULL,
    "CreditCardAuth" VARCHAR(6) NULL,
    "AuthorizationStatu" SMALLINT NULL,
    "CreditCardNote" VARCHAR(128) NULL,
    "LastActivityDate" VARCHAR(30) NULL,
    "CreditCardAmountAuth" DECIMAL(19,4) NULL,
    "Comment2" VARCHAR(2000) NULL,
    "Comment3" VARCHAR(160) NULL,
    "BeforeInvoiceRef" TINYINT NULL,
    "enECommerceSale" INT NULL,
    "ShipByDate" VARCHAR(30) NULL,
    "ReturnAuthorization" VARCHAR(20) NULL,
    "UseDirectDeposit" INT NULL,
    "DirDepCmpnyAcctNumb" VARCHAR(48) NULL,
    "DirDepCmpnyRtngNumb" VARCHAR(24) NULL,
    "IsDDDistLocked1" INT NULL,
    "TransactionCode1" SMALLINT NULL,
    "AccountNumber1" VARCHAR(48) NULL,
    "RoutingNumber1" VARCHAR(24) NULL,
    "DrctDpstGUID1" VARCHAR(32) NULL,
    "AmtPctToDistribute1" DECIMAL(19,4) NULL,
    "Amount1" DECIMAL(19,4) NULL,
    "AllocationMethod1" INT NULL,
    "IsDDDistLocked2" INT NULL,
    "TransactionCode2" SMALLINT NULL,
    "AccountNumber2" VARCHAR(48) NULL,
    "RoutingNumber2" VARCHAR(24) NULL,
    "DrctDpstGUID2" VARCHAR(32) NULL,
    "AmtPctToDistribute2" DECIMAL(19,4) NULL,
    "Amount2" DECIMAL(19,4) NULL,
    "AllocationMethod2" INT NULL,
    "IsDDDistLocked3" INT NULL,
    "TransactionCode3" SMALLINT NULL,
    "AccountNumber3" VARCHAR(48) NULL,
    "RoutingNumber3" VARCHAR(24) NULL,
    "DrctDpstGUID3" VARCHAR(32) NULL,
    "AmtPctToDistribute3" DECIMAL(19,4) NULL,
    "Amount3" DECIMAL(19,4) NULL,
    "AllocationMethod3" INT NULL,
    "IsDDDistLocked4" INT NULL,
    "TransactionCode4" SMALLINT NULL,
    "AccountNumber4" VARCHAR(48) NULL,
    "RoutingNumber4" VARCHAR(24) NULL,
    "DrctDpstGUID4" VARCHAR(32) NULL,
    "AmtPctToDistribute4" DECIMAL(19,4) NULL,
    "Amount4" DECIMAL(19,4) NULL,
    "AllocationMethod4" INT NULL,
    "LastUpdateCounter" INT NULL,
    "FromRegister" TINYINT NULL,
    "SuperRecordNumber" INT NULL,
    "CustomerSONo" VARCHAR(20) NULL,
    "AppName" VARCHAR(14) NULL,
    "ProposalAccepted" TINYINT NULL,
    "PayMethod" SMALLINT NULL,
    "LastPostedAt" VARCHAR(30) NULL,
    "IsManualPayrollCheck" TINYINT NULL,
    "PayMethodRecNum" INT NULL,
    "CCRelatedTrx" INT NULL,
    "CC_VANReference" VARCHAR(16) NULL,
    "_lote_id" VARCHAR(40) NOT NULL,
    "_propiedad_origen" VARCHAR(30) NOT NULL,
    "_dsn_origen" VARCHAR(50) NOT NULL,
    "_archivo_origen" VARCHAR(400) NOT NULL,
    "_cargado_en" DATETIME2(3) NOT NULL
);
GO


-- ----------------------------------------------------------------------------
-- bronze.lote -- registro de cada corrida de carga. No sale del esquema de
-- Sage, es propia del pipeline -- el generador no la toca.
-- ----------------------------------------------------------------------------
CREATE TABLE bronze.lote (
    lote_id           VARCHAR(40)  NOT NULL,
    propiedad_origen  VARCHAR(30)  NOT NULL,
    dsn_origen        VARCHAR(50)  NOT NULL,
    extraido_en       DATETIME2(3) NULL,
    cargado_en        DATETIME2(3) NOT NULL,
    tabla             VARCHAR(30)  NOT NULL,
    filas_origen      INT          NOT NULL,
    CONSTRAINT pk_bronze_lote PRIMARY KEY NONCLUSTERED (lote_id, tabla) NOT ENFORCED
);
GO
